### ISSUE TITLE
Don't set the font size of the body element

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-components#228]
> font sizes it is even better to use em. The idea is (1) to not set the font size of the BODY element (in HTML), but use the default size of the device, because that is a size that the reader can comfortably read

https://www.w3.org/Style/Examples/007/units.html

As I understand from this document, sizes in rem has no difference with sizes in pixels because we have set [font-size: 16px to html and body](https://github.com/aeternity/aepp-components/blob/15cf40c71a019d2bedf91720268abf356f38cb94/src/styles/rules.scss#L18) elements.

**Comment by sadiqevani** [comment]
https://github.com/aeternity/aepp-components/pull/236

**Comment by sadiqevani** [comment]
Closing this due to PR being opened.
