### ISSUE TITLE
Make backdrop transparency adjustable

### ISSUE THREAD

**Issue by kenodressel** [aeternity/aepp-components#230]
The ae-backdrop component has a low alpha value which makes containing text hard to read. It would be good to let the user adjust the backdrops transparency for their purpose.

**Comment by sadiqevani** [comment]
@kenodressel how are you using backdrop? Its not meant to work as standalone with text over it. It should mainly contain:

- Modals
- List box items
- Panels (a component which I think needs to be developed)

**Comment by kenodressel** [comment]
Currently the header on non-mobile devices reads "Go To Main Page" in addition to the specified title as './assets/logo-small.png' can not be loaded. Other than this the styling looks significantly better compared to when i initially opened this issue.

**Comment by kenodressel** [comment]
Okay that was a error on my side then. I added ae-card ontop of the backdrop but ae-panel would be nice to have in the future.
