### ISSUE TITLE
Should AeText become deprecated?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-components#238]
This component looks super similar to `font` tag. For some reason, `font` tag marked as [obsolete](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font) in HTML 4, 5. I think we should investigate why this happened and ensure that usage of AeText is not a bad practice.

**Comment by sadiqevani** [comment]
This is a bit out of a scope, with `aepp-components` we're not trying to define the HTML5 or 6 or define any standards, we're developing components to make our apps easier to build. I don't see any point in removing `ae-text` as it lets you define text based on the typography we have. So its consistent throughout the applications.
