### ISSUE TITLE
aeButton; why emitting click event on click?

### ISSUE THREAD

**Issue by dadaphl** [aeternity/aepp-components#32]
Whats the benefit of emitting the click event on click? As far as i know, the click event can be registered to any component.

https://github.com/aeternity/aepp-components/blob/6ae8825d7a5ecbf56e8018b40db80364ae43cee1/src/components/aeButton/aeButton.vue#L2

**Comment by acdbaykal** [comment]
@dadaphl,

I inserted 

````js
new Vue({
  data(){ return { modalVisible: false } },
  template: `
    <ae-button plain type="dramatic" @click="onClick">Plain dramatic</ae-button>
  `,
  methods:{
    onClick: function() {
      console.log('CLICK')
    }
  }
})
````

into aeButton.md and manually tested the behavior. When I remove that line I don't get a "CLICK" output on the console. So (oddly) it appears to be necessary.
