### ISSUE TITLE
chevron.svg and chevron-down.svg

### ISSUE THREAD

**Issue by dadaphl** [aeternity/aepp-components#49]
chevron-down is just a 90deg rotated chevron, can we come up with a solution to rotate icons? We could introduce a prop for that or some dynamic resolution of rotation by name-rotation

```
name : ${icon-name}-${icon-rotation}
```

**Comment by davidyuk** [comment]
I think will be better to implement rotation as a separate prop of AeIcon.

**Comment by acdbaykal** [comment]
@dadaphl,
nice suggestion but be aware that this is a breaking change. We'll need to make a major version bump to avoid breaks in apps who use chevron-down

**Comment by davidyuk** [comment]
Lately, we have so a lot of breaking changes what I'm not sure that we should increase major version. Let's stuck somewhere in 2.x.x and add a notice that this api is not stable yet.
`chevron-down` probably used only in AeAmountInput.

**Comment by acdbaykal** [comment]
Issue was resolved (#59)
