### ISSUE TITLE
Refactor identity

### ISSUE THREAD

**Issue by acdbaykal** [aeternity/aepp-components#78]
The Identity components themselves should only contain the information about the identity without any background. The card like container should become a separate component of its own. Then anyone can just add any buttons they like into these card like containers.

[![Screenshot-2018-3-21_Zeplin_-_Project.png](https://s17.postimg.org/m3p1d6qhr/Screenshot-2018-3-21_Zeplin_-_Project.png)](https://postimg.org/image/l1euun7ob/)

[![Screenshot-2018-3-21_Zeplin_-_Project_1.png](https://s17.postimg.org/co95zylbj/Screenshot-2018-3-21_Zeplin_-_Project_1.png)](https://postimg.org/image/gkmhvy6az/)

**Comment by acdbaykal** [comment]
For further clarification. aeIdenity should become limitted to these areas **(without background and without margin)**

[![Ids.png](https://s17.postimg.org/m228haaof/Ids.png)](https://postimg.org/image/gqnbwkoln/)

**Comment by Philip-Nunoo** [comment]
https://github.com/aeternity/aepp-components/pull/80 update available here

**Comment by acdbaykal** [comment]
The solution is part of Branch update-identities now
